project:
  type: r3-theme

book:
  title: "Analysis of mechanisms"
  subtitle: "Modern mediation analysis for basic, clinical and epidemiological research in diabetes and endocrinology"
  author:
    - "Daniel B. Ibsen"
    - "Omar Silverman"
    - "Jie Zhang"
    - "Nima Hejazi"
    - "Iván Díaz"
  site-url: "https://analysis-of-mechanisms.netlify.app"
  repo-url: "https://github.com/steno-aarhus/mediation-analysis-course"
  chapters:
    - index.qmd
    - part: "Preamble"
      chapters:
      - preamble/pre-course.qmd
    - part: "Sessions"
      chapters:
      - sessions/motivation-for-mediation-analysis.qmd
      - sessions/traditional-mediation-analysis.qmd
      - sessions/causal-mediation-analysis-introduction.qmd
      - sessions/group_work_day1.qmd
      - sessions/causal-mediation-analysis-estimation.qmd
      - sessions/causal-mediation-analysis-survival-outcomes.qmd
      - sessions/causal-mediation-analysis-sensitivity-analysis.qmd
      - sessions/reporting-guidelines.qmd
      - sessions/mcma_preface.qmd
      - sessions/mcma_effects_defn.qmd
      - sessions/mcma_choosing_effects.qmd
      - sessions/group_work_day2.qmd
      - sessions/mcma_estim_prelims.qmd
      - sessions/mcma_estim_natural_interv.qmd
      - sessions/mcma_estim_walkthru.qmd
      - sessions/mcma_longit_effects.qmd
      - sessions/NetCoupler-example.qmd
  appendices:
    - appendices/references.qmd
    - appendices/mcma_stoch_effects.qmd
    - appendices/mcma_addl_readings.qmd
    - LICENSE.md
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.html

bibliography:
  - includes/papers.bib
csl: includes/the-american-journal-of-clinical-nutrition.csl

editor:
  markdown:
    wrap: 72
    canonical: true

format:
  r3-theme-html

execute:
  freeze: false
